### PR TITLE
2nd Pass R Assignment 6

### PR DESCRIPTION
**Pull request by brymz**
(As per #75) 
Major renaming and file shuffling to get titles in numerical order.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Did you use `git mv` for this renaming or did you do it some other way? I ask because the diff here is really confusing since it looks like massive changes are being made to the exercises when they're really just being renamed. This might be unavoidable since you're renaming them to the names of other existing files, but if it is avoidable we should try to do so.

**Comment by brymz** [comment]
I did not use `git mv`, mostly because I needed to move a set of files to a
place holder so they didn't 'already exist'. Should I try to make the file
move and edits separate PRs? Might run into merge problems that way.

**Comment by ethanwhite** [comment]
Ah, right, that makes sense. Can you explain a little more about why you needed to do the renames. We really don't want the build to be dependent on having the order in the assignment match the numbering anyway.

**Comment by brymz** [comment]
The original names were 'Graphing 2', 'Graphing 3', 'Graphing 1'. I think
this would seem really odd to someone who was trying to work with our
material. Most of the titles are already in numeric order now because I
cleaned them up as I was going along (e.g., Expressions and Variables,
Making Choices). Expressions and Variables and Making Choices dropped
unused exercises and condensed title order, which gave me the place holder
position when renaming. I chose to make the rename for Graphing in the
second pass to push off the ugliness from all of the direct overlap in
names with no obvious place holder to a point when the site was getting
established.  The build is still completely dependent on exercise title,
which happens to be in numeric order when appropriate for ease of use.

**Comment by ethanwhite** [comment]
OK, got it. Let's just eat the ugly history on this one and get it done. Thanks!

**Comment by brymz** [comment]
Thanks. :: sigh :: Tried to keep it all in one place.

**Pull request merged**
