### PR TITLE
2nd Pass R Assignment 3

### PR DESCRIPTION
**Pull request by brymz**

### CODE REVIEW

**Comment by ethanwhite** [comment]
Looks like we have an auto-merge issue here as well.

**Comment by brymz** [comment]
Yep. Not sure exactly what's going on here.
I changed the r-2.md to r-3.md, but it didn't resolve.
Can I get git to tell me where the conflict is?

**Comment by ethanwhite** [comment]
I see you got this figured out, but for future reference - If you try to 
go a local version of the merge it should tell you where the conflict 
is. You can either create a fresh branch off of master and try to do 
your merge into it, or you can try to merge into master using 
http://stackoverflow.com/questions/501407/is-there-a-git-merge-dry-run-option 
and see what happens.

Ethan

**Comment by brymz** [comment]
See #124 and #125

**Pull request closed without merging**
